config/routes.rb
Eter::Application.routes.draw do
  resources :badges

  resources :events

  resources :awards

  resources :editorials

  resources :users
  
  resources :points, :only => [:index, :show, :destroy]

  root :to => "home#index"

end

app/models/award.rb
class Award < ActiveRecord::Base
  validates :name, presence: true
end

app/models/badge.rb
class Badge < ActiveRecord::Base
  validates :name, :description, :media, :url, :award_id, presence: true

  belongs_to :award
  belongs_to :event
end

app/models/editorial.rb
class Editorial < ActiveRecord::Base
  validates :uri, :presence => true 
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, :editorial_id, :points, :presence => true
  validates :points, :numericality => true

  belongs_to :editorial
end

app/models/point.rb
class Point < ActiveRecord::Base
  validates :user_name, :event, :badge, :points, presence: true
  
  belongs_to :user
  belongs_to :event
  belongs_to :badge
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true
end

app/controllers/awards_controller.rb
class AwardsController < ObjectsController

  def get_class
    Award
  end

  def field_for_search
    "name"
  end

end

app/controllers/badges_controller.rb
class BadgesController < ObjectsController
  def get_class
    Badge
  end

  def field_for_search
    "name"
  end
end

app/controllers/editorials_controller.rb
class EditorialsController < ObjectsController
  def get_class
    Editorial
  end

  def field_for_search
    "uri"
  end
end

app/controllers/events_controller.rb
class EventsController < ObjectsController
  def get_class
    Event
  end

  def field_for_search
    "name"
  end
end

app/controllers/objects_controller.rb
class ObjectsController < ApplicationController
  respond_to :html, :json

  def get_class
  end

  def get_object_identifier
    name = get_class().name.downcase
    name.to_sym
  end

  def get_objects_identifier
    name = get_object_identifier.to_s
    name = name.pluralize
    name.to_sym
  end

  def set_variable_collection
    variable = ("@" + get_objects_identifier.to_s).to_sym
    instance_variable_set variable, @objects
  end

  def set_variable
    variable = ("@" + get_object_identifier.to_s).to_sym
    instance_variable_set variable, @object
  end

  # GET /objects
  # GET /objects.json

  def field_for_search
  end

  def index
    @objects = get_class.paginate(:per_page => 10, :page => params[:page],
                                  :conditions => ["#{field_for_search} like ?", params[:search] + "%"],
                                  :order => "#{field_for_search} ASC") if params[:search]

    @objects = get_class.paginate(:per_page => 10, :page => params[:page]) if params[:search] == nil
    set_variable_collection
    respond_with @objects
  end

  # GET /objects/1
  # GET /objects/1.json
  def show
    @object = get_class.find(params[:id])
    set_variable
    respond_with @object
  end

  # GET /objects/new
  # GET /objects/new.json
  def new
    @object = get_class.new
    set_variable
  end

  # GET /objects/1/edit
  def edit
    @object = get_class.find(params[:id])
    set_variable
    respond_with @object
  end

  # POST /objects
  # POST /objects.json
  def create
    @object = get_class.new(params[get_object_identifier])
    set_variable
    @object.save
    respond_with @object
  end

  # PUT /objects/1
  # PUT /objects/1.json
  def update
    @object = get_class.find(params[:id])
    set_variable

    if @object.update_attributes(params[get_object_identifier])
      respond_with @object
    else
      render :action => 'edit'
    end
  end

  # DELETE /objects/1
  # DELETE /objects/1.json
  def destroy
    @object = get_class.find(params[:id])
    @object.destroy
    redirect_to get_objects_identifier
  end
end

app/controllers/points_controller.rb
class PointsController < ObjectsController
  def get_class
    Point
  end

  def field_for_search
    "points"
  end
end

app/controllers/users_controller.rb
class UsersController < ObjectsController
  def get_class
    User
  end

  def field_for_search
    "name"
  end

end

app/helpers/awards_helper.rb
module AwardsHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/editorials_helper.rb
module EditorialsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/awards/_form.html.erb
<%= form_for(@award) do |f| %>
  <% if @award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% @award.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/awards/edit.html.erb
<h1>Editing award</h1>

<%= render 'form' %>

<%= link_to 'Show', @award %> |
<%= link_to 'Back', awards_path %>

app/views/awards/index.html.erb
<h1>Listing awards</h1>
<%= form_tag request.path, :method => 'get' do %>
  <% content_tag :label do %>
    Search :
    <%= text_field_tag :search, params[:search]%>
  <% end %>
<% end %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @awards.each do |award| %>
  <tr>
    <td><%= award.name %></td>
    <td><%= award.description %></td>
    <td><%= award.url %></td>
    <td><%= link_to 'Show', award, :class => 'btn btn-mini'%></td>
    <td><%= link_to 'Edit', edit_award_path(award) , :class => 'btn btn-mini'%></td>
    <td><%= link_to 'Destroy', award, confirm: 'Are you sure?', method: :delete , :class => 'btn btn-mini btn-danger'%></td>
  </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @users %>

<%= link_to 'New Award', new_award_path, :class => 'btn btn-mini btn-lista-adicionar' %>

app/views/awards/new.html.erb
<h1>New award</h1>

<%= render 'form' %>

<%= link_to 'Back', awards_path %>

app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @award.name %>
</p>

<p>
  <b>Description:</b>
  <%= @award.description %>
</p>

<p>
  <b>Url:</b>
  <%= @award.url %>
</p>


<%= link_to 'Edit', edit_award_path(@award) %> |
<%= link_to 'Back', awards_path %>

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :point_min %>
    <%= f.number_field :point_min %>
  </div>
  <div class="field">
    <%= f.label :unique %>
    <%= f.check_box :unique %>
  </div>
  <div class="field">
    <%= f.label :shared %>
    <%= f.check_box :shared %>
  </div>
  <div class="field">
    <%= f.label :media %>
    <%= f.text_field :media %>
  </div>
  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :award %>
    <%= f.text_field :award_id %>
  </div>
  <div class="field">
    <%= f.label :event %>
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>
<%= form_tag request.path, :method => 'get' do %>
  <% content_tag :label do %>
    Search :
    <%= text_field_tag :search, params[:search]%>
  <% end %>
<% end %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Point min</th>
    <th>Unique</th>
    <th>Shared</th>
    <th>Media</th>
    <th>Url</th>
    <th>Award</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @badges.each do |badge| %>
  <tr>
    <td><%= badge.name %></td>
    <td><%= badge.description %></td>
    <td><%= badge.point_min %></td>
    <td><%= badge.unique %></td>
    <td><%= badge.shared %></td>
    <td><%= badge.media %></td>
    <td><%= badge.url %></td>
    <td><%= badge.award.name %></td>
    <td><%= badge.event.name %></td>
    <td><%= link_to 'Show', badge, :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Edit', edit_badge_path(badge), :class => 'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', badge, confirm: 'Are you sure?', method: :delete, :class => 'btn btn-mini btn-danger' %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @users %>

<%= link_to 'New Badge', new_badge_path, :class => 'btn btn-mini btn-lista-adicionar' %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @badge.name %>
</p>

<p>
  <b>Description:</b>
  <%= @badge.description %>
</p>

<p>
  <b>Point min:</b>
  <%= @badge.point_min %>
</p>

<p>
  <b>Unique:</b>
  <%= @badge.unique %>
</p>

<p>
  <b>Shared:</b>
  <%= @badge.shared %>
</p>

<p>
  <b>Media:</b>
  <%= @badge.media %>
</p>

<p>
  <b>Url:</b>
  <%= @badge.url %>
</p>

<p>
  <b>Award:</b>
  <%= @badge.award.name %>
</p>

<p>
  <b>Event:</b>
  <%= @badge.event.name %>
</p>


<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>

app/views/editorials/_form.html.erb
<%= form_for(@editorial) do |f| %>
  <% if @editorial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@editorial.errors.count, "error") %> prohibited this editorial from being saved:</h2>

      <ul>
      <% @editorial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uri %>
    <%= f.text_field :uri %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/editorials/edit.html.erb
<h1>Editing editorial</h1>

<%= render 'form' %>

<%= link_to 'Show', @editorial %> |
<%= link_to 'Back', editorials_path %>

app/views/editorials/index.html.erb
<h1>Listing editorials</h1>
<%= form_tag request.path, :method => 'get' do %>
  <% content_tag :label do %>
    Search :
    <%= text_field_tag :search, params[:search]%>
  <% end %>
<% end %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Uri</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @editorials.each do |editorial| %>
  <tr>
    <td><%= editorial.uri %></td>
    <td><%= link_to 'Show', editorial, :class => 'btn btn-mini'%></td>
    <td><%= link_to 'Edit', edit_editorial_path(editorial) , :class => 'btn btn-mini'%></td>
    <td><%= link_to 'Destroy', editorial, confirm: 'Are you sure?', method: :delete , :class => 'btn btn-mini btn-danger'%></td>
  </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @editorials %>

<%= link_to 'New Editorial', new_editorial_path, :class => 'btn btn-mini btn-lista-adicionar' %>

app/views/editorials/new.html.erb
<h1>New editorial</h1>

<%= render 'form' %>

<%= link_to 'Back', editorials_path %>

app/views/editorials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uri:</b>
  <%= @editorial.uri %>
</p>


<%= link_to 'Edit', edit_editorial_path(@editorial) %> |
<%= link_to 'Back', editorials_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :points %>
    <%= f.number_field :points %>
  </div>
  <div class="field">
    <%= f.label :editorial_id %>
    <%= f.text_field :editorial_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>
<%= form_tag request.path, :method => 'get' do %>
  <% content_tag :label do %>
    Search :
    <%= text_field_tag :search, params[:search]%>
  <% end %>
<% end %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Points</th>
    <th>Editorial</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @events.each do |event| %>
  <tr>
    <td><%= event.name %></td>
    <td><%= event.points %></td>
    <td><%= event.editorial.uri %></td>
    <td><%= link_to 'Show', event, :class=>'btn btn-mini'%></td>
    <td><%= link_to 'Edit', edit_event_path(event) , :class=>'btn btn-mini'%></td>
    <td><%= link_to 'Destroy', event, confirm: 'Are you sure?', method: :delete, :class=>'btn btn-mini btn-danger' %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @events %>

<%= link_to 'New Event', new_event_path, :class => 'btn btn-mini btn-lista-adicionar' %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Points:</b>
  <%= @event.points %>
</p>

<p>
  <b>Editorial:</b>
  <%= @event.editorial.uri %>
</p>


<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_path %>">Eter</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Awards", awards_path %></li>
            <li><%= link_to "Badges", badges_path %></li>
            <li><%= link_to "Editorials", editorials_path %></li>
            <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Points", points_path %></li>
            <li><%= link_to "Users", users_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

<div class="container">
    <div class="row">
        <div class="span12">
            <%= yield %>
        </div>
    </div>
</div>
</body>
</html>

app/views/points/index.html.erb
<h1>Listing Points</h1>
<%= form_tag request.path, :method => 'get' do %>
  <% content_tag :label do %>
    Search :
    <%= text_field_tag :search, params[:search]%>
  <% end %>
<% end %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Points</th>
    <th>Badge</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @points.each do |point| %>
  <tr>
    <td><%= point.user.name %></td>
    <td><%= point.points %></td>
    <td><%= point.badge.name %></td>
    <td><%= link_to 'Show', point, :class=>'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', point, confirm: 'Are you sure?', method: :delete, :class=>'btn btn-mini btn-danger' %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<%= will_paginate @Points %>

app/views/points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @point.user.name %>
</p>

<p>
  <b>Points:</b>
  <%= @point.points %>
</p>

<p>
  <b>Badge:</b>
  <%= @point.badge.name %>
</p>

<%= link_to 'Back', points_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :oauth_token %>
    <%= f.text_field :oauth_token %>
  </div>
  <div class="field">
    <%= f.label :oauth_token_secret %>
    <%= f.text_field :oauth_token_secret %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<%= form_tag request.path, :method => 'get' do %>
  <% content_tag :label do %>
    Search :
    <%= text_field_tag :search, params[:search]%>
  <% end %>
<% end %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Oauth token</th>
    <th>Oauth token secret</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.oauth_token %></td>
    <td><%= user.oauth_token_secret %></td>
    <td><%= link_to 'Show', user, :class=>'btn btn-mini' %></td>
    <td><%= link_to 'Edit', edit_user_path(user), :class=>'btn btn-mini' %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete, :class=>'btn btn-mini btn-danger' %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @users %>

<%= link_to 'New User', new_user_path, :class => 'btn btn-mini btn-lista-adicionar' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Oauth token:</b>
  <%= @user.oauth_token %>
</p>

<p>
  <b>Oauth token secret:</b>
  <%= @user.oauth_token_secret %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>